Initial-commit
shalithasuranga/runn pull request #10
Opened 2020-01-07 17:44 UTC by 0sf

I have updated the README.md I would love to hear what are the mistakes I made and correct them ASAP.

2020-01-10 12:23 UTC, shalithasuranga commented on README.md
> +This project was built using JavaScript
Could you removed this section because anyone can see this from Github

2020-01-10 12:24 UTC, shalithasuranga commented on README.md
> +Make your own terminal aliases easily!
Could you start with "Runn is command line tool which will make y..... etc"

2020-01-10 12:25 UTC, shalithasuranga commented on README.md
> +npm install npm@latest -g
Could you add $ to start

2020-01-10 12:26 UTC, shalithasuranga commented on README.md
> +Contributions are what make the open source community such an amazing place to be learn, inspire, and create. Any contributions you make are **greatly appreciated**.
maybe we can remove bold formatting ?

2020-01-10 12:27 UTC, shalithasuranga commented on README.md
> -MIT
We can remove "See `LICENSE` for more information." and add link to License with MIT instead

2020-01-10 12:27 UTC, shalithasuranga requested changes
Thanks for the nice improvements. Could you please check inline comments and updated the PR

2020-01-10 15:46 UTC, 0sf commented
@shalithasuranga Thank you for suggestions. I have corrected them with your guidelines. Please let me know if there are any mistakes. Thank you.

2020-01-11 03:04 UTC, shalithasuranga approved these changes
Nice work 👍

2020-01-11 03:04 UTC, merged